services:
  arai-db:
    image: postgres:15-alpine
    container_name: arai-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-arai2026}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - arai-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - arai-network

  arai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arai-app
    restart: always
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-arai_user}:${POSTGRES_PASSWORD:-arai_password}@arai-db:5432/${POSTGRES_DB:-arai_db}?schema=public
      NEXTAUTH_URL: https://yerbamatearai.com.ar
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_DOMAIN: yerbamatearai.com.ar
    depends_on:
      - arai-db
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - arai-network

networks:
  arai-network:
    driver: bridge

volumes:
  arai-db-data:
